#!/bin/sh
#BSUB -L /bin/sh
#BSUB -J Fluid-Only
#BSUB -q ccs_long
#BSUB -W 168:00
#BSUB -o %J.out
#BSUB -e %J.err
#BSUB -n 2
#BSUB -u mgay@tulane.edu

echo Start Job
date
pwd

cd RUN1
./IFEM &

cd ../

cd RUN2
./IFEM &

wait

echo End Job
