#!/bin/sh
#BSUB -L /bin/sh
#BSUB -J Leaflet34
#BSUB -q fsi_short
#BSUB -W 24:00
#BSUB -o %J.out
#BSUB -e %J.err
#BSUB -n 2
#BSUB -u mgay@tulane.edu

echo Start Job
date
pwd

cd Run3/
bpsh $NODES ./IFEM &

cd ../

cd Run4/
bpsh  $NODES ./IFEM &

wait

echo End Job
